[package]
name = "super-2048"
version = "0.1.0"
authors = ["Scoder12 <34356756+Scoder12@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "super-2048"
path = "main.rs"
